# Generated by Django 2.2.14 on 2021-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champagneblogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
