# Generated by Django 2.2.14 on 2021-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0003_champagneblogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagneblogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
