# Generated by Django 2.2.14 on 2021-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0004_auto_20210404_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagneblogpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
