# Generated by Django 2.2.14 on 2021-04-05 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0006_champagneblogpost_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champagneblogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='champagneblogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='champagneblogpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champagneblogpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
