# Generated by Django 3.1.7 on 2021-04-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0007_auto_20210405_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='champagneblogpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
