# Generated by Django 2.2.14 on 2021-04-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0008_champagneblogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagneblogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
